apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cep0001-run
  namespace: tekton-namespace
  annotations:
    config.kubernetes.io/depends-on: tekton.dev/namespaces/tekton-namespace/Pipeline/cep0001
spec:
  params:
    - name: namespace
      value: chaos-namespace
    - name: test
      value: testvalue
  pipelineRef:
    name: cep0001
