apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: replacements-target-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
  namespace: target-namespace
replacements:
  - source:
      kind: TargetNamespace
      fieldPath: metadata.name
    targets:
      - select:
          kind: PipelineRun
        fieldPaths:
          - spec.params.[name=namespace].value
  - source:
      kind: Secret
      name: kubeconfig-target-cluster
      fieldPath: metadata.name
    targets:
      - select:
          kind: PipelineRun
        fieldPaths:
          - spec.workspaces.[name=kubeconfig-dir].secret.secretName

