apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata: # kpt-merge: target-namespace/replacements-target-namespace
  name: replacements-target-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'fn.kpt.dev|ApplyReplacements|target-namespace|replacements-target-namespace'
  namespace: target-namespace
replacements:
  - source:
      kind: TargetNamespace
      fieldPath: metadata.name
    targets:
      - select:
          kind: PipelineRun
        fieldPaths:
          - spec.params.[name=namespace].value
