apiVersion: fn.kpt.dev/v1alpha1
kind: RenderHelmChart
metadata:
  name: notImportantHere
  annotations:
    config.kubernetes.io/function: |
      container:
        network: true
        image: gcr.io/kpt-fn/render-helm-chart:v0.2.0
helmCharts:
  - chartArgs:
      repo: https://bitnami-labs.github.io/sealed-secrets
      version: 2.6.9
      name: sealed-secrets
      namespace: kube-system

