apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cep0001
  namespace: tekton-namespace
spec:
  description: |
    TBD. include-file @cep0001.md
  params:
    - name: namespace
      type: string
      description: Target namespace where to apply
  tasks:
    - name: k-get-pods-before
      taskRef:
        name: kubernetes-actions
      params:
        - name: script
          value: |
            set -e
            kubectl get pods -n $(params.namespace)
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
    - name: apply-chaos
      taskRef:
        name: chaosmesh-pod-kill
      params:
        - name: namespace
          value: $(params.namespace)
      runAfter:
        - k-get-pods-before
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
    - name: k-get-pods-after
      taskRef:
        name: kubernetes-actions
      params:
        - name: script
          value: |
            set -e
            kubectl get pods -n $(params.namespace)
      runAfter:
        - apply-chaos
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
  workspaces:
    - name: kubeconfig-dir
      description: kubeconfig secret
