apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
resources:
  - https://api.hub.tekton.dev/v1/resource/tekton/task/kubernetes-actions/0.2/raw
