apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: chaosmesh-pod-kill
spec:
  description: Apply pod-failure with ChaosMesh
  params:
    - description: where to apply chaos
      name: namespace
      type: string
    - default: bash
      name: image
    - name: chaos-mesh-yaml
      type: string
      default: |
        kind: PodChaos
        apiVersion: chaos-mesh.org/v1alpha1
        metadata:
          namespace: $(params.namespace)
          generateName: pod-failure-
        spec:
          selector:
            namespaces:
              - $(params.namespace)
            labelSelectors:
              app.kubernetes.io/component: master
              app.kubernetes.io/name: redis
          mode: one
          action: pod-kill
          gracePeriod: 0
  results:
    - description: some result can be emitted if someone wants to.
      name: output-result
  steps:
    - image: $(params.image)
      name: kubectl
      script: |
        #!/usr/bin/env bash
        set -e
        
        cm=$(cat <<EOF
        $(params.chaos-mesh-yaml)
        EOF
        )
        echo $cm