apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgAHhE5ERWQY+ZiMiFXDaa4/G5BY9tASKTfpL04Q7HcobZ7FvHVRqk2waANVGqTrOhxBj+N9fo1p/Z3+XznrbqRpcJdIMv1LYkYIJzEhH4bnalmM4FjbKh73ZwGPIlKUFEiwEwvbmF7TVKAKV9dfvPraGhxGNWyqR66gLc5Mf5mgDf1xaE16UeXGjqVp/jHI2U/rcUiksuSK3FaqB6qBtvwGOJXxXCAKoAUTEzVgfsjA7fAMWiQXYL/wrnbfsIG5Tz8+l93ekP510zn8ijF4/LNvLckPtfhaQw8/9r2O9Vzevon1WicGHC7pyC/f7iK9PcL3uDYkqdgglyxxKh+tx8nwT1nYWlviAtMudk9k0D8VmsW3kIrZ2VLly6VRXeFMRSpp61/XMBnPaalOdbBc0niJIx6sqw+bAQBjg6nsqBKtx4lE2R0UQenHiXCaRucDJBMZiYj3P5OqgzPftjO9M3Z+UZqKDuPvS3Tg/NiCugEbDZGCGIinNjCF9GP4zi65bYIOP9AE8UGZ7n+EJjAR5eDLIJfkCmGnnknLrScHSvblF3Pijlt/6L5YgrOGABC5bwI+y56TlF/njIZJ+cyc5CF4aAofrWaIM0nS2ErzUbw0SH3cnlYnd3tzR5Pag2YnFesBXbtg/YaRFs1/WEA/Hz599z7NhWm382XzAdKzwqK99GAbpN6c7hNn8jmJ4H82OY4A1xg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

