apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: example
  name: example
spec:
  containers:
  - command: ["kubectl"]
    args: ["get", "pods", "-n", "kube-system"]
    image: bitnami/kubectl
    env:
    - name: KUBECONFIG
      value: "/.kube/kubeconfig"
    volumeMounts:
    - name: kubeconfig
      mountPath: "/.kube"
      readOnly: true
    name: example
    resources: {}
  volumes:
  - name: kubeconfig
    secret:
      secretName: kubeconfig-example
      optional: false
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
