apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: change-image-proxy
params:
  gcr.io: proxy.company.com
source: |-
  def is_kpt_file(r):
    return r["kind"] == "Kptfile"
  def ensureProxy(resources, gcrioProxy):
    for resource in resources:
      if not is_kpt_file(resource):
        return
      for m in resource["pipeline"]["mutators"]:
        m["image"] = m["image"].replace("gcr.io", gcrioProxy)
  gcrio_proxy = ctx.resource_list["functionConfig"]["params"]["gcr.io"]
  ensureProxy(ctx.resource_list["items"], gcrio_proxy)
