apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: replacements-target-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
  - source:
      kind: TargetNamespace
      fieldPath: metadata.name
    targets:
      - select:
          kind: PipelineRun
        fieldPaths:
          - spec.params.[name=namespace].value
