apiVersion: v1
kind: Namespace
metadata:
    name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: echo-deployment
    namespace: app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: echo-server
    template:
        metadata:
            labels:
                app: echo-server
        spec:
            containers:
                - name: echo-server
                  image: hashicorp/http-echo
                  args:
                      - -text="hello world"
                  ports:
                      - name: http-port
                        containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
    name: echo-service
    namespace: app
spec:
    ports:
        - name: http-port
          port: 5678
          targetPort: 5678
          protocol: TCP
    selector:
        app: echo-server