apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cep0002
  namespace: tekton-namespace
spec:
  description:
    TBD. include-file @cep0001.md
  params:
    - name: namespace
      type: string
      description: Target namespace where to apply
    - name: chaos-mesh-yaml
      type: string
      description: Chaos Mesh pod kill yaml
  tasks:
    - name: k-get-pods-before
      taskRef:
        name: kubernetes-actions
      params:
        - name: script
          value: |
            set -e
            kubectl get pods -n $(params.namespace)
            echo "$(params.test)"
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
    - name: apply-chaos
      taskRef:
        name: kubernetes-actions
      params:
        - name: script
          value: |
            set -e
            echo $(params.chaos-mesh-yaml) | kubectl apply -f -
      runAfter:
        - k-get-pods-before
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
    - name: k-get-pods-after
      taskRef:
        name: kubernetes-actions
      params:
        - name: script
          value: |
            set -e
            kubectl get pods -n $(params.namespace)
      runAfter:
        - apply-chaos
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
  workspaces:
    - name: kubeconfig-dir
