apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-run-set-default-status
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  by-value: kubeconfig-example
  by-path: data.by-value
  put-value: kubeconfig-example-XXXXXX
